### ISSUE TITLE
Weird indentation

### ISSUE THREAD

**Issue by bokub** [amio/badgen-service#137]
When viewing badgen on my linux machine with **chromium**, the _Usage_ indentation is broken.

> Version 63.0.3239.84 Built on Ubuntu , running on Ubuntu 17.04 (64 bits)

![image](https://user-images.githubusercontent.com/17952318/45025514-fc76c000-b03b-11e8-96ec-60bbbcd24ce1.png)

**Comment by styfle** [comment]
Try adding CSS for 

```css
pre {
    font-family: monospace;
}

code {
    font-family: monospace;
}

```

See if one of those works 🤷‍♂️
